# Generated by Django 4.2.4 on 2023-08-08 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receitasApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitas',
            name='categoria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receitasApp.categoria'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='receita_imagem',
            field=models.ImageField(blank=True, default='', upload_to='receitas/receitas_imagens/%d/%m/%Y/'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
