# Generated by Django 4.2.4 on 2023-10-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagApp', '0002_remove_tag_content_type_remove_tag_object_id'),
        ('receitasApp', '0002_alter_receitas_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitas',
            name='tags',
            field=models.ManyToManyField(to='tagApp.tag'),
        ),
    ]
