# Generated by Django 4.2.4 on 2023-10-01 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='object_id',
        ),
    ]
